<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BackupPhotographersSeeder extends Seeder
{
    public function run()
    {
        DB::table('photographers')->insert([
            [
                'id' => 9,
                'user_id' => 11,
                'google_id' => null,
                'name' => 'Pradeep Silva',
                'email' => 'pradeep.silva@gmail.com',
                'contact' => '+94 77 567 8901',
                'password' => '$2y$12$AHicYSLU8e0km5eBXiSu1.r8ODaBrPeVFGljUQNwfUU7sz5wnWO1i',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-14 05:07:32',
                'updated_at' => '2025-09-23 07:02:19',
                'bio' => 'Experienced event photographer covering concerts & corporate gigs.',
                'categories' => 'wedding,outdoor',
                'location' => 'Dambulla',
                'experience' => 3,
                'languages' => null,
                'profile_image' => 'photographers/PBJFMqMqMyotV0fpl6cboDsrnCcR1P9wnErZf2S8.jpg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
            [
                'id' => 10,
                'user_id' => 12,
                'google_id' => null,
                'name' => 'Chamara Perera',
                'email' => 'chamara.perera@gmail.com',
                'contact' => '+94 77 123 4567',
                'password' => '$2y$12$qslYJ69XHjHrLAm.E26UCuDYhfOl7XbM0MRmNRSki/4dFgpIJW6ZK',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-14 05:14:28',
                'updated_at' => '2025-08-16 06:31:14',
                'bio' => 'Specialist in cinematic wedding photography with 5+ years’ exp.',
                'categories' => 'wedding,outdoor',
                'location' => 'Colombo',
                'experience' => 6,
                'languages' => 'Sinhala, English',
                'profile_image' => 'photographers\chamara.jpeg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
            [
                'id' => 11,
                'user_id' => 13,
                'google_id' => null,
                'name' => 'Nadeesha Fernando',
                'email' => 'nadeesha.f@gmail.com',
                'contact' => '+94 71 987 6543',
                'password' => '$2y$12$7mnHp8Bjk8Fh5ZsH8jp8xeEwtWhLbXfAYqHbEq1jrKIjbDfJ4nPCi',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-14 05:14:38',
                'updated_at' => '2025-08-16 06:31:14',
                'bio' => 'Passionate about fashion & editorial shoots, modern styles.',
                'categories' => 'outdoor,fashion',
                'location' => 'Kandy',
                'experience' => 4,
                'languages' => 'Sinhala, English',
                'profile_image' => 'photographers\nadeesha.jpeg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
            [
                'id' => 12,
                'user_id' => 14,
                'google_id' => null,
                'name' => 'Isuru Jayawardena',
                'email' => 'isuru.jay@gmail.com',
                'contact' => '+94 76 345 6789',
                'password' => '$2y$12$NVFssdOnGckiFns861dtmuixF6VqkZhvBDtcjYoNoZX4wc3NoE6S.',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-14 05:14:45',
                'updated_at' => '2025-08-16 06:31:14',
                'bio' => 'Portrait photographer capturing natural expressions.',
                'categories' => 'birthday,fashion',
                'location' => 'Galle',
                'experience' => 4,
                'languages' => 'Sinhala, Tamil, English',
                'profile_image' => 'photographers\isuru.jpg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
            [
                'id' => 13,
                'user_id' => 15,
                'google_id' => null,
                'name' => 'Sanduni Perera',
                'email' => 'sanduni.perera@gmail.com',
                'contact' => '+94 71 234 5678',
                'password' => '$2y$12$B3Hv9mlVDwpan0HYfTY4UeDDfS6eheQ6pBuq.UOqWFr0P1gHBNN8S',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-14 05:14:53',
                'updated_at' => '2025-08-16 06:31:14',
                'bio' => 'Passionate about fashion & editorial shoots, modern styles.',
                'categories' => 'outdoor,fashion',
                'location' => 'Negombo',
                'experience' => 2,
                'languages' => 'Sinhala, English',
                'profile_image' => 'photographers\sanduni.jpg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
            [
                'id' => 14,
                'user_id' => 16,
                'google_id' => null,
                'name' => 'Tharindu Wijesinghe',
                'email' => 'tharindu.w@gmail.com',
                'contact' => '+94 72 345 6789',
                'password' => '$2y$12$cIhpfh/DpgnBIFyPUJkbqOSDUG4c9f9ST54Mp00TZulrPatLuVu4i',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-14 05:15:01',
                'updated_at' => '2025-08-16 06:31:14',
                'bio' => 'Landscape and travel photographer inspired by hill country beauty.',
                'categories' => 'wedding,birthday,outdoor',
                'location' => 'Nuwara Eliya',
                'experience' => 6,
                'languages' => 'Sinhala, Tamil, English',
                'profile_image' => 'photographers\tharindu.jpg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
            [
                'id' => 15,
                'user_id' => 17,
                'google_id' => null,
                'name' => 'Ayesha Jayasinghe',
                'email' => 'ayesha.jaya@gmail.com',
                'contact' => '+94 77 890 1234',
                'password' => '$2y$12$2n/CutSXe70Ylq2w8zhj5uX4dTtB/SqUL4swhqagMNV8UnVZtnqfa',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-14 05:15:09',
                'updated_at' => '2025-08-16 06:31:14',
                'bio' => 'Young fashion photographer with creative urban style.',
                'categories' => 'birthday,outdoor,fashion',
                'location' => 'Colombo',
                'experience' => 3,
                'languages' => 'Sinhala, English',
                'profile_image' => 'photographers\ayesha.jpeg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
            [
                'id' => 22,
                'user_id' => 32,
                'google_id' => null,
                'name' => 'Dilini Ratnayake',
                'email' => 'dilini.rat@gmail.com',
                'contact' => '+94 76 123 0987',
                'password' => '$2y$12$9RmOaSIOYJejhyLGA2zgLuVdp6fylkXAR5GoFUU9ddAjSGn9w1Zd2',
                'role' => 'photographer',
                'google_profile_data' => null,
                'is_google_registered' => 0,
                'created_at' => '2025-08-20 04:09:33',
                'updated_at' => '2025-08-20 04:09:33',
                'bio' => 'Creative fashion photographer with a keen eye for style and detail. I specialize in capturing bold, elegant, and timeless images that bring out individuality and confidence in every shoot.',
                'categories' => 'wedding,fashion',
                'location' => 'Colombo',
                'experience' => 3,
                'languages' => 'English',
                'profile_image' => 'photographers\dilini.jpg',
                'instagram' => null,
                'facebook' => null,
                'website' => null,
                'availability' => null,
                'is_verified' => 0,
            ],
        ]);
    }
}
