<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BackupUsersSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Bihangi Yohansa',
                'email' => 'bihangi@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$wakcMyHCWw7vVd3RkqM0muzEW1tSxG5pgFsj.jqKLJF4wkFpwsjM2',
                'role' => 'client',
                'location' => 'Kandy',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => '2025-07-26 17:48:58',
                'contact' => '0723344556',
            ],
            [
                'id' => 3,
                'name' => 'Admin',
                'email' => 'pickapic.admin@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$pfKpQLu7oGqfcRtvkZC3fOAjq4JaWcfBhmlodDeNFfcbdxf3YZ1va',
                'role' => 'admin',
                'location' => '-',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => '2025-07-27 15:51:43',
                'contact' => null,
            ],
            [
                'id' => 11,
                'name' => 'Pradeep Silva',
                'email' => 'pradeep.silva@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$AHicYSLU8e0km5eBXiSu1.r8ODaBrPeVFGljUQNwfUU7sz5wnWO1i',
                'role' => 'photographer',
                'location' => 'Kandy',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:07:32',
                'updated_at' => '2025-09-03 11:55:06',
                'contact' => '+94 77 567 8901',
            ],
            [
                'id' => 12,
                'name' => 'Chamara Perera',
                'email' => 'chamara.perera@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$qslYJ69XHjHrLAm.E26UCuDYhfOl7XbM0MRmNRSki/4dFgpIJW6ZK',
                'role' => 'photographer',
                'location' => 'Colombo',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:14:28',
                'updated_at' => '2025-08-14 05:14:28',
                'contact' => '+94 77 123 4567',
            ],
            [
                'id' => 13,
                'name' => 'Nadeesha Fernando',
                'email' => 'nadeesha.f@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$7mnHp8Bjk8Fh5ZsH8jp8xeEwtWhLbXfAYqHbEq1jrKIjbDfJ4nPCi',
                'role' => 'photographer',
                'location' => 'Kandy',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:14:38',
                'updated_at' => '2025-08-14 05:14:38',
                'contact' => '+94 71 987 6543',
            ],
            [
                'id' => 14,
                'name' => 'Isuru Jayawardena',
                'email' => 'isuru.jay@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$NVFssdOnGckiFns861dtmuixF6VqkZhvBDtcjYoNoZX4wc3NoE6S.',
                'role' => 'photographer',
                'location' => 'Galle',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:14:45',
                'updated_at' => '2025-08-14 05:14:45',
                'contact' => '+94 76 345 6789',
            ],
            [
                'id' => 15,
                'name' => 'Sanduni Perera',
                'email' => 'sanduni.perera@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$B3Hv9mlVDwpan0HYfTY4UeDDfS6eheQ6pBuq.UOqWFr0P1gHBNN8S',
                'role' => 'photographer',
                'location' => 'Negombo',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:14:53',
                'updated_at' => '2025-08-14 05:14:53',
                'contact' => '+94 71 234 5678',
            ],
            [
                'id' => 16,
                'name' => 'Tharindu Wijesinghe',
                'email' => 'tharindu.w@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$cIhpfh/DpgnBIFyPUJkbqOSDUG4c9f9ST54Mp00TZulrPatLuVu4i',
                'role' => 'photographer',
                'location' => 'Nuwara Eliya',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:15:01',
                'updated_at' => '2025-08-14 05:15:01',
                'contact' => '+94 72 345 6789',
            ],
            [
                'id' => 17,
                'name' => 'Ayesha Jayasinghe',
                'email' => 'ayesha.jaya@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$2n/CutSXe70Ylq2w8zhj5uX4dTtB/SqUL4swhqagMNV8UnVZtnqfa',
                'role' => 'photographer',
                'location' => 'Colombo',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:15:09',
                'updated_at' => '2025-08-14 05:15:09',
                'contact' => '+94 77 890 1234',
            ],
            [
                'id' => 18,
                'name' => 'Nirmala Fernando',
                'email' => 'nirmala.fernando@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$XYRYvW.29x9U/hkWkQpXruAw934eYhbb2pYai8BU4GIVbM38sClV.',
                'role' => 'client',
                'location' => 'Colombo',
                'remember_token' => null,
                'created_at' => '2025-08-14 05:16:25',
                'updated_at' => '2025-08-14 05:16:25',
                'contact' => null,
            ],
            [
                'id' => 25,
                'name' => 'Roshan Abeywardena',
                'email' => 'roshan.abey@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$TmqlQN2C212plCiP0.vs8uS6ltQbkrQOA/ZbpInh6dxBFONKEFFJ.',
                'role' => 'photographer',
                'location' => 'Kandy',
                'remember_token' => null,
                'created_at' => '2025-08-20 00:14:37',
                'updated_at' => '2025-08-20 00:14:37',
                'contact' => '+94 71 678 9012',
            ],
            [
                'id' => 32,
                'name' => 'Dilini Ratnayake',
                'email' => 'dilini.rat@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$9RmOaSIOYJejhyLGA2zgLuVdp6fylkXAR5GoFUU9ddAjSGn9w1Zd2',
                'role' => 'photographer',
                'location' => 'Colombo',
                'remember_token' => null,
                'created_at' => '2025-08-20 04:09:33',
                'updated_at' => '2025-08-20 04:09:33',
                'contact' => '+94 76 123 0987',
            ],
        ]);
    }
}
