[variables]
NIXPACKS_PHP_ROOT_DIR = '/'
NIXPACKS_PHP_FALLBACK_PATH = '/public/index.php'

[providers.php]
extensions = ["pdo_mysql", "mysqli"]

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[phases.deploy]
cmds = [
    'php artisan migrate --force',
    'php artisan db:seed --force'
]